
backend:
  name: "github"
  repo: "PrometheusConsulting/prometheusconsulting.github.io" # Path to your Github repositor
  branch: "develop"
  base_url: "https://prometheus-software-backend.herokuapp.com"
publish_mode: "editorial_workflow"
display_url: https://prometheusconsulting.io
media_folder: "src/assets/images"
public_folder: "/"
collections:
  - name: "pages"  # Used in routes, e.g., /admin/collections/blog
    label: "Pages"  # Used in the UI
    format: 'json'
    files: [
      {
        label: 'Home Page',
        name: 'home',
        file: 'src/assets/cms/home.json',
        fields: [ # The fields for each document
          {
            label: "Sections",
            name: "sections",
            widget: "list",
            default: [],
            fields: [
              {
                label: "Type",
                name: "type",
                widget: 'select',
                default: 'DEFAULT',
                options: [
                  'DEFAULT',
                  'IMAGE',
                ],
              },
              {
                label: "Title",
                name: "title",
                widget: "string",
              },
              {
                label: "Subtitle",
                name: "subtitle",
                widget: "string",
              },
              {
                label: "Call to Action",
                name: "cta",
                widget: "string",
              },
              {
                label: "Image",
                required: false,
                name: "image",
                widget: "image",
              },
              {
                label: 'Bulma Classes (camelCase)',
                name: "bulma",
                widget: "list",
                default: [],
              },
            ],
          },
        ]
      },
    ]
