
backend:
  name: "github"
  repo: "PrometheusConsulting/prometheusconsulting.github.io" # Path to your Github repositor
  branch: "master"
  base_url: "https://prometheus-software-backend.herokuapp.com"
publish_mode: "editorial_workflow"
media_folder: "static/media/uploads"
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "/blog" # The path to the folder where the documents are stored
    format: "json"
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}