
backend:
  name: github
  branch: master # Branch to update (optional; defaults to master)
  repo: PrometheusConsulting/prometheusconsulting.github.io
publish_mode: editorial_workflow
media_folder: '/uploads'
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts/blog" # The path to the folder where the documents are stored
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
